### ISSUE TITLE
[L] DUP - Site metrics results reflect when facilities were noted as "pass not required" 

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-reso-admin#312]
## Description
This ticket is meant to align DUP capacity with the actual status of the park. Currently, the status of the facility does not influence capacity, so our reports require manual adjustment. 

Let's make DUP the source of truth for this data.

For a given day, if the capacity is set to 200 for an example, and if the passes are marked as required, then the metrics page should reflect the capacity as 200. Similarly, if for a different day, the capacity is set to 200 but for the same day the passes are marked as NOT REQUIRED, then the capacity shouldn't be displayed as 200 in the metrics. 

## Acceptance Criteria

Given that I am seeking accurate DUP data on the site metrics page 
When I populate the page or pull a report 
Then I see data that reflects the actual capacity 

Give that I am viewing the metric page for a day where the passes are set to "Not required" from the facility level
When I populate the Metrics page and export the excel report
Then I should see that the base capacities are also set to zero in the exported report. 

<img width="1337" alt="Image" src="https://github.com/user-attachments/assets/405d41ee-dca4-4c11-a6b2-effb56275ad1" />

Development Checklist:

- [x] Metrics page accounts for passes not required when displaying graphs
- [x] Metrics report accounts for passes not required and will change capacity to 0 for those days. 
- [x] Any passes booked prior to passes not required will persist as booked passes (Do not change these to 0, May be addressed in future ticket)
- Note: At a quick glance the Passes required value is not being stored in the reservations object in db. Initial thought is to include this in the write metrics job to be used in metrics reporting.  

Old links (TBC)
Carefully identify the resources to be abandoned

## Linked issues
is blocked by
- [x] https://github.com/bcgov/parks-reso-api/issues/309

**Comment by LindsayMacfarlane** [comment]
November 21, 2024 - DUP prioritization session. This ticket/issue was identified as medium-high priority. Additional feedback:

- Marshall identified that this is a high priority as the current DUP dataset is not seen as the 'source of truth'.
- To have accurate data, the program team is manual checking/updating in an excel spreadsheet


https://app.mural.co/t/bcparks2575/m/bcparks2575/1729124366479/8adea59d9e76fb3eb1e33395f1c1857a8c07fb7b

**Comment by Dianadec** [comment]
Refinement notes: 
What can we do to make it a source of truth now vs. how we'll define capacity in the new system? (Spike: Discuss the way that we define capacity in the new system in general. Marshall/Niamh/Lindsay ??)

**Comment by Dianadec** [comment]
Manuji's perspective:
Note: 
Ideal to see - have Marshall share his screen to show what ideally needs to be done.

**Comment by Dianadec** [comment]
Had a refinement meeting Feb 20 to discuss this ticket in more detail with @MarshallHenson @Christopher-walsh22 @manuji - see recording: [Refining DUP Ticket - 'Pass not required'-20250220_101553-Meeting Recording](https://bcgov-my.sharepoint.com/personal/diana_decotiis_gov_bc_ca/_layouts/15/stream.aspx?id=%2Fpersonal%2Fdiana%5Fdecotiis%5Fgov%5Fbc%5Fca%2FDocuments%2FRecordings%2FRefining%20DUP%20Ticket%20%2D%20%27Pass%20not%20required%27%2D20250220%5F101553%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E4ebd1469%2Db6fa%2D4622%2D999b%2D612f0d74de85)
Next steps - refine ticket based on meeting notes. Reminder to keep the first step as the main fix, and other asks/pieces of work can be captured in future tickets.

**Comment by LindsayMacfarlane** [comment]
@Dianadec and @manuji - can one of you take a pass at updating this ticket based on your conversation with Marshall. Thanks!

**Comment by Dianadec** [comment]
@manuji  updated the description/ac (thank you!!). Sending for estimates. @LindsayMacfarlane

**Comment by davidclaveau** [comment]
@manuji this is ready to be moved to TEST and reviewed!

I've made it so any changes to a park or a facility for "Passes Required" will correctly reflect in the "Base Capacity" and "Available Passes" metrics.

![Image](https://github.com/user-attachments/assets/6498c849-ab1c-4be8-a9ac-6e8d7567ae1d)
![Image](https://github.com/user-attachments/assets/5545cb2e-0816-44c8-89ad-5a9d8f64cef0)

However, this will only update the Metrics section of the app after the `metrics` function runs. This metrics function doesn't update often in DEV/TEST (just three times a day at 1am, 8am, and 5pm), so I can help with testing and run it manually as needed! All I would need to do is trigger the function and it will run this metrics function and update accordingly on the Metrics page.

Hope that makes sense - let me know if/when I can help with that!

**Comment by manuji** [comment]
This ticket is blocked by a defect in the booking a pass workflow.

**Comment by manuji** [comment]
Tested on TEST:
* Verified when it is set to "Passes are not required at this park" from the park edit page, the exported report correctly show the the Passes required as False and the base capacities as zero. 
* Verified that from the Facility edit page is the facility is set to Closed, then the exported report shows the status as Closed. If it is set to Open, then it will show it as Open in the exported report. 

@davidclaveau when I had the passes required: on days selected below and none were selected, the exported report showed passes required as TRUE (even after I ran the wriremetrics labda function). Could you please check again on TEST?


**Questions:**
1. If the park is open and passes are required at the park level, from the facility level and if the facility is closed but still the passes required is set to Every day (or some days), in this case should the exported report show zero base capacity? Given below is how it shows on exported report; 

![Image](https://github.com/user-attachments/assets/7985e1cd-c39f-4bde-8026-b2557c41df5e)

![Image](https://github.com/user-attachments/assets/0e108fc6-8e28-4ff3-b4c0-59f6deea890e)

**Comment by MarshallHenson** [comment]
Note: in practice, we almost never use the facility-level closed button (deselecting dates triggers a text field, so that is the preferred method of "closing" a facility). Happy to have it included in the "set" of buttons that triggers this capacity override but the DoW requirements and the park-level pass requirements are the two important triggers for this exercise.

**Comment by manuji** [comment]
Thanks @MarshallHenson

**Comment by davidclaveau** [comment]
@manuji this is in DEV and should be ready for testing!

The facility's status now properly affects whether passes are required and the capacity amounts on the metrics page when we change that facility-level button. 

I also found that the park's overall status wasn't applying the same logic, so a park could be closed but the facility would still be showing as open with passes available and capacities at their normal amounts.

> when I had the passes required: on days selected below and none were selected, the exported report showed passes required as TRUE (even after I ran the wriremetrics labda function). Could you please check again on TEST?

I think there was a bug with how the `reservation` object was being written (there was a bug when attempting to retrieve the `park` object to check the park's status and apply all of that logic) - I was getting errors on my local and things were being a little wonky, but still _kinda_ worked. I wrote some tests and it looks like this is being applied now, so this should be all fixed!

Let me know if you have any questions during your testing!

**Comment by manuji** [comment]
Tested on TEST: **Pending**

| Park Level pass required  | Facility is open |Pass required  |Test result|
| ------------- | ------------- |------------- | -------------|
| True  | True  |Everyday  | Passes/Failed |
| True | True  |None | Passes/Failed |
| True  | False  |Everyday | Passes/Failed |
| True  | False  |None | Passes/Failed |
| False | True |Everyday | Passes/Failed |
| False  | True  |None  | Passes/Failed |
| False | False|Everyday | Passes/Failed |
| False  | False  |None |Passes/Failed |

**Comment by davidclaveau** [comment]
@manuji ah yea ok I just remembered an important piece of how metrics are created.

So the reason these tests were failing is because that the metrics table/spreadsheet is partially built off the `reservations` object, which holds the facility's capacity and open/closed status for the day. This `reservations` object is created just the one time (only when the first pass is booked for the day, or when/if the facility is changed and saved that day - whichever comes first).
 
So any changes that we make to the facility, either retroactively for previous days or for today, won't apply the change for that `Passes required` or the `AM, PM, All-day` capacities columns because the facility was already saved earlier. I remember noting this as it coincided with what Marshall requested, i.e. we don't want things to be overwritten retroactively by facility changes.
 
I was able to test these changes by going into Dynamo and deleting the `reservations::0007::Cheakamus` for `2025-05-02` object. Once it's deleted, the next time I save the facility the changes are applied for that day only, and that creates a new object with the updates.

Let me know if that works for your testing and if you have any questions!

**Comment by manuji** [comment]
Tested on TEST: **Pending**

All the scenarios passed except for one given below;

| Park Level pass required  | Facility is open |Pass required  |Test result|
| ------------- | ------------- |------------- | -------------|
| False | True |Everyday | Failed-> Passes required shows as True |

**Comment by manuji** [comment]
Tested on TEST: **Passed**

| Park Level pass required  | Facility is open |Pass required  |Test result|
| ------------- | ------------- |------------- | -------------|
| True  | True  |Everyday  | Passed -> Status = open, Passes required = TRUE |
| True | True  |None | Passed -> Status = open, Passes required = FALSE |
| True  | False  |Everyday | Passed -> Status = closed, Passes required = FALSE |
| True  | False  |None | Passed -> Status = closed, Passes required = FALSE |
| False | True |Everyday | Passed -> Status = closed, Passes required = FALSE |
| False  | True  |None  | Passed-> Status = closed, Passes required = FALSE |
| False | False|Everyday | Passed -> Status = closed, Passes required = FALSE |
| False  | False  |None | Passed -> Status = closed, Passes required = FALSE |

* This issue fix has been passed and ready for UAT and PO review. fyi @MarshallHenson & @LindsayMacfarlane .

**Comment by MarshallHenson** [comment]
Logic in the table presented in the most recent comment is congruent with expectations. @manuji have you tested scenarios with partial daily pass requirements (ie. Saturday & Sunday only)?

**Comment by MarshallHenson** [comment]
Awesome. Looks great!

**Comment by manuji** [comment]
Thank you @MarshallHenson

**Comment by LindsayMacfarlane** [comment]
Tested by both @manuji and @MarshallHenson. Approved. 

Thank you @davidclaveau for tackling this ticket. It will be great that DUP can become the source of truth for the data and decrease the need for program staff to run their own metrics/calculations.

**Comment by manuji** [comment]
Deployed to PROD.
