### ISSUE TITLE
Implement UI for DUP Admin Advanced Booking of Passes

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-reso-admin#316]
## Description

As a BC Parks staff I want to book off X number of passes prior to them being available so that I can accommodate groups like Canucks Autism and Park Bus planning parks visits moving forward.

## Acceptance Criteria:

* BC Parks admin user (sys admin role) can book of any number of passes on admin DUP and those passes become reserved

## Linked issues

is blocked by

- [x] ~[BRS-595](https://bcparksdigital.atlassian.net/browse/BRS-595)~

- [x] ~[BRS-694](https://bcparksdigital.atlassian.net/browse/BRS-694)~

relates to

- [ ] [BRS-986](https://bcparksdigital.atlassian.net/browse/BRS-986)

**Comment by kgorana** [comment]
**Jessica Wade** 
August 19, 2022 at 4:03 PM

@janemoxd @ndelraye @meredithom no rush on this but tagging for designs and AC

**Comment by MarshallHenson** [comment]
This has not been completed. Admin users have the ability to reduce the number of passes but not to reserve them.

**Comment by LindsayMacfarlane** [comment]
November 21, 2024 - DUP prioritization session. This ticket/issue was identified as medium priority.

https://app.mural.co/t/bcparks2575/m/bcparks2575/1729124366479/8adea59d9e76fb3eb1e33395f1c1857a8c07fb7b
